# Generated by Django 4.2.2 on 2024-01-06 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleeaseapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('gst_no', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('doc_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('doc_type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MesgMaster',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mesg_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MesgTran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_mesg', models.CharField(max_length=500, null=True)),
                ('receiver_mesg', models.CharField(max_length=500, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleeaseapi.mesgmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
                ('photo', models.CharField(max_length=60)),
                ('fname', models.CharField(max_length=40)),
                ('mname', models.CharField(max_length=40, null=True)),
                ('lname', models.CharField(max_length=40, null=True)),
                ('role', models.SmallIntegerField()),
                ('gender', models.SmallIntegerField(null=True)),
                ('dob', models.DateField()),
                ('user_status', models.SmallIntegerField()),
                ('profile_status', models.SmallIntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleeaseapi.city')),
                ('gst_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduleeaseapi.companydetails')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_path', models.CharField(max_length=500, unique=True)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleeaseapi.doctype')),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleeaseapi.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('project_des', models.CharField(max_length=1000, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleeaseapi.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_path', models.CharField(max_length=500, unique=True)),
                ('doc_access', models.SmallIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleeaseapi.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.SmallIntegerField()),
                ('joined_on', models.DateField()),
                ('removed_on', models.DateField(null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleeaseapi.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleeaseapi.project')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleeaseapi.country')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=20)),
                ('task_desc', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField(null=True)),
                ('deadline', models.DateField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_tasks', to='scheduleeaseapi.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleeaseapi.project')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member_tasks', to='scheduleeaseapi.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_path', models.CharField(max_length=500, unique=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleeaseapi.task')),
            ],
        ),
        migrations.DeleteModel(
            name='TASK_TBL',
        ),
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleeaseapi.profile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleeaseapi.project'),
        ),
        migrations.AddField(
            model_name='mesgmaster',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='scheduleeaseapi.profile'),
        ),
        migrations.AddField(
            model_name='mesgmaster',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='scheduleeaseapi.profile'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleeaseapi.state'),
        ),
    ]
