# Generated by Django 4.2.2 on 2024-01-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleeaseapi', '0003_alter_profile_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mesgmaster',
            table='MesgMaster',
        ),
        migrations.AlterModelTable(
            name='mesgtran',
            table='MesgTran',
        ),
        migrations.AlterModelTable(
            name='projectmember',
            table='ProjectMember',
        ),
        migrations.AlterModelTable(
            name='task',
            table='Task',
        ),
    ]
