# Generated by Django 4.2.2 on 2024-01-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleeaseapi', '0004_alter_mesgmaster_table_alter_mesgtran_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
