# Generated by Django 4.2.2 on 2024-01-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleeaseapi', '0005_alter_profile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='City',
        ),
        migrations.AlterModelTable(
            name='companydetails',
            table='CompanyDetails',
        ),
        migrations.AlterModelTable(
            name='country',
            table='Country',
        ),
        migrations.AlterModelTable(
            name='doctype',
            table='DocType',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='Payment',
        ),
        migrations.AlterModelTable(
            name='profiledocument',
            table='ProfileDocument',
        ),
        migrations.AlterModelTable(
            name='project',
            table='Project',
        ),
        migrations.AlterModelTable(
            name='projectdocument',
            table='ProjectDocument',
        ),
        migrations.AlterModelTable(
            name='state',
            table='State',
        ),
        migrations.AlterModelTable(
            name='taskdocument',
            table='TaskDocument',
        ),
    ]
