# Generated by Django 4.2.2 on 2024-01-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleeaseapi', '0006_alter_city_table_alter_companydetails_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='state',
            new_name='state_id',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='country',
            new_name='country_id',
        ),
    ]
