# Generated by Django 4.2.2 on 2024-01-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleeaseapi', '0008_rename_state_id_city_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
