# Generated by Django 4.2.2 on 2024-01-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleeaseapi', '0009_project_budget_alter_project_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='gst_no',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
