# Generated by Django 4.2.2 on 2024-02-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleeaseapi', '0013_alter_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='gst_no',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
